#include "assembler.h"

#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include "utils.h"
#include "pseudoinstructions.h"
#include "instructions.h"

/*
 Assembler

 Takes as input a Text structure generated by the Preprocessor and the path to the output file
 Performs two passes:
  - The first pass parses the lines from the input into instructions and data,
      and adds symbol declarations to the symbol table.
      It returns InstructionList, DataList, and SymbolTable structures.
  - The second pass converts each instruction into its 32-bit machine code representation
      by consulting the InstructionTable and writes it to the output file, consulting
      the symbol table when needed. It then writes the raw data to file.

 Both passes take as input an Assembler structure, which contains pointers to the
  Text, InstructionList, DataList, SymbolTable, and InstructionTable structures. This is generated by the main
  assemble() function.
*/

enum DataType CURRENT_DIRECTIVE = WORD; // Keeps track of the type of data item being stored; assumes WORD by default
Segment CURRENT_SEGMENT = TEXT;         // Keeps track of current segment being read; assmes TEXT by default

/* === FIRST PASS TEXT SEGMENT === */

// Parses a string into an Instruction. Does most of the heavy-lifting for this part of the assembler.
int parse_instruction(const Assembler *assembler, Line *line, Instruction *instruction) {
    const char *line_text = line_get_str(line);
    if (line_text == NULL) return 0;
    memset(instruction->mnemonic, '\0', sizeof(instruction->mnemonic));

    const Immediate imm = {NONE, .intValue=0, .modifier=0};
    instruction->imm = imm;

    char line_buf[strlen(line_text) + 1]; // Tokenize a copy so we preserve original string
    strcpy(line_buf, line_text);

    char *token = tokenize(line_buf, ' ');
    int argc = 0;
    unsigned char args[3];
    unsigned char readMnemonic = 0; // Whether the mnemonic has been read. Set to true when the assembler finds the first token not ending in ':'
    char *cur;

    String label;
    try(string_init(&label), 0);

    // Loop through each token
    while (token != NULL) {
        size_t len = strlen(token);

        // Check if token is a label
        if (token[len-1] == ':') {
            // Check for errors
            if (readMnemonic || len <= 1) { // Labels should not be empty and should not come after the mnemonic
                raise_error(SYMBOL_INV, token, __FILE__);
                return 0;
            }
            if (isdigit(token[0])) {
                raise_error(SYMBOL_INV, token, __FILE__);
                return 0;
            }

            // Copy over symbol
            for (size_t i = 0; i < len-1; i++) {
                if ( !issymbol(token[i]) ) {
                    raise_error(SYMBOL_INV, token, __FILE__);
                    return 0;
                }
                string_set(&label, i, token[i]);
            }

            // Add to symbol table (assumes local, but if it exists as global, will preserve that binding)
            if (CURRENT_SEGMENT == TEXT) {
                try(st_add_symbol(assembler->symbol_table, label.str, assembler->instruction_list->text_offset, TEXT, LOCAL), 0);
            } else if (CURRENT_SEGMENT == KTEXT) {
                try(st_add_symbol(assembler->symbol_table, label.str, assembler->kernel_text->text_offset, KTEXT, LOCAL), 0);
            }
            string_clear(&label);
        }

        // Read mnemonic. This will catch the first token not ending in ':' and set readMnemonic to true.
        else if (!readMnemonic) {
            if (len >= MNEMONIC_LENGTH) {
                raise_error(SIZE_ERR, token, __FILE__);
                return 0;
            }
            strcpy(instruction->mnemonic, token);
            readMnemonic = 1;
        }

        // Process arguments
        else {
            if (argc >= 3) {
                raise_error(ARG_INV, token, __FILE__);
                return 0;
            }

            // Read register
            if (token[0] == '$') {

                const unsigned char r = get_register(token);
                if (r == 255) {
                    // Failed, assume immediate
                    goto is_imm;
                }

                args[argc] = r;
                argc++;
            }

            // If argument doesn't start with $, assume immediate
            else {

                is_imm:
                // Special check for if tokenize removed a space character
                cur = token;
                if (cur[0] == '"' && cur[1] == '\0') {
                    cur[1] = ' ';
                    token = tokenize(NULL, ' ');
                    if (token == NULL || token[0] != '"') {
                        raise_error(ARG_INV, cur, __FILE__);
                        return 0;
                    }
                }
                instruction->imm = parse_imm(cur, assembler->symbol_table, 1);
                if (instruction->imm.modifier == 255) {
                    return 0;
                }
                token = tokenize(NULL, ' ');
                if (token != NULL) { // Make sure there's no arguments after
                    raise_error(ARG_INV, token, __FILE__);
                    return 0;
                }

                break;
            }
        }

        token = tokenize(NULL, ' ');
    }

    string_destroy(&label);

    // Add registers
    int i;
    for (i = 0; i < argc; i++) { // Add registers to list
        instruction->registers[i] = args[i];
    }
    while (i < 3) { // Fill remaining spaces with 255
        instruction->registers[i] = 255;
        i++;
    }

    return 1;
}

// Adds Instruction to InstructionList, and converts special instructions
int process_instruction(const Instruction instruction, InstructionList *instruction_list) {

    // Check special case: `li` (load immediate)
    // necessary because assembler currently doesn't support %hi and %lo for numerical values
    if (strcmp(instruction.mnemonic, "li") == 0) {
        if (li(instruction, instruction_list) == -1) {
            return 0;
        }
        return 1;
    }

    return add_instruction(instruction_list, instruction);

}

// Parses and processes a Line containing an instruction.
int read_text(const Assembler *assembler, Line *line) {

    Instruction instruction;
    int success = parse_instruction(assembler, line, &instruction);
    try(success, 0);
    instruction.line = line;

    // Add to instruction list
    if (CURRENT_SEGMENT == TEXT) {
        try(process_instruction(instruction, assembler->instruction_list), 0);
    }
    else if (CURRENT_SEGMENT == KTEXT) {
        try(process_instruction(instruction, assembler->kernel_text), 0);
    }

    return 1;
}

/* === FIRST PASS DATA SEGMENT === */

// Processes a Line containing data. Parses and adds to the DataList simultaneously.
int read_data(const Assembler *assembler, const Line *line) {

    char *text = line_get_str(line);
    if (text == NULL) return 0;
    char line_buffer[strlen(text) + 1]; // Use a separate buffer to avoid overwriting the input string
    strcpy(line_buffer, text);

    // Tokenize
    char *token = tokenize(line_buffer, ' ');
    int argc = 0; // Number of data items stored
    int readDirective = 0; // Whether the directive has been read. Set to true by the assembler when it finds the first token not ending in ':'

    String labels[16]; // Supports up to 16 labels at a time. Should be enough. Who is declaring 16 duplicate labels?
    size_t label_count = 0;

    size_t argument_size = 32;
    char *argument = malloc(argument_size);
    if (argument == NULL) {
        raise_error(MEM, NULL, __FILE__);
        return 0;
    }

    DataList *list = NULL;
    if (CURRENT_SEGMENT == DATA) {
        list = assembler->data_list;
    }
    else if (CURRENT_SEGMENT == KDATA) {
        list = assembler->kernel_data;
    }
    else {
        free(argument);
        return 0;
    }

    while (token != NULL) {
        const size_t len = strlen(token);
        if (len <= 0) continue;

        // Token is a label
        if (token[len-1] == ':' && token[0] != '"') {
            string_init(&labels[label_count]);

            // Set aside label, add to symbol list later
            // We set it aside because the directive may add padding before the data it stores, and we don't know the directive yet
            if (strlen(token) <= 1 || readDirective) { // Labels should not be empty and should precede the mnemonic
                raise_error(ARG_INV, token, __FILE__);
                free(argument);
                return 0;
            }
            if (isdigit(token[0])) {
                raise_error(SYMBOL_INV, token, __FILE__);
                free(argument);
                return 0;
            }

            for (size_t i = 0; i < strlen(token)-1; i++) {
                if ( !issymbol(token[i]) ) {
                    raise_error(SYMBOL_INV, token, __FILE__);
                    free(argument);
                    return 0;
                }
                string_set(&labels[label_count], i, token[i]);
            }
            label_count++;

            token = tokenize(NULL, ' ');
            continue;
        }

        // Token is a directive; update CURRENT_DIRECTIVE and sets readDirective to 1.
        if (!readDirective) { // Catches the first token not ending in ':'
            char directive[8];
            memset(directive, '\0', sizeof(directive));
            strncpy(directive, token, strlen(token)); // copy just the name
            if (read_directive(directive, &CURRENT_DIRECTIVE) == 0) {
                free(argument);
                return 0;
            }
            readDirective = 1;
        }

        // Token is an argument (i.e., a data item to store)
        else {
            if (CURRENT_DIRECTIVE == ALIGN) {
                if (argc != 0) { // Should only have one argument
                    raise_error(ARGS_INV, NULL, __FILE__);
                    free(argument);
                    return 0;
                }

                // Parse to integer
                if (add_aligned(line, token, list) == 0) {
                    free(argument);
                    return 0;
                }

                // Save label(s) (after alignment)
                if (label_count != 0) {
                    for (size_t i = 0; i < label_count; i++) {
                        if (st_add_symbol(assembler->symbol_table, labels[i].str, list->data_offset, CURRENT_SEGMENT, LOCAL) == 0) {
                            free(argument);
                            return 0;
                        }
                    }
                }

            }
            else if (CURRENT_DIRECTIVE == SPACE) {
                if (argc != 0) {
                    free(argument);
                    raise_error(ARGS_INV, NULL, __FILE__);
                    return 0;
                }

                // Save label(s) (before adding space)
                if (label_count != 0) {
                    for (size_t i = 0; i < label_count; i++) {
                        if (st_add_symbol(assembler->symbol_table, labels[i].str, list->data_offset, CURRENT_SEGMENT, LOCAL) == 0) {
                            free(argument);
                            return 0;
                        }
                    }
                }

                // Parse to integer
                if (add_space(line, token, list) == 0) {
                    free(argument);
                    return 0;
                }
            }
            else {
                memset(argument, '\0', argument_size);
                int string_length = 0;

                // Argument is a string; note I keep the quotes to differentiate strings from other data (namely labels)
                if (token[0] == '"') {
                    argument = read_string(argument, &argument_size, token, &string_length);
                    if (argument == NULL) {
                        return 0;
                    }
                }

                // Argument is not a string
                else {
                    if (len >= argument_size) {
                        argument_size *= 2;
                        char *new = realloc(argument, argument_size);
                        if (new == NULL) {
                            raise_error(MEM, NULL, __FILE__);
                            free(argument);
                            return 0;
                        }
                        argument = new;
                    }
                    strcpy(argument, token);
                }

                // Create data object
                Data data;
                data.line = line;
                // save the size before processing. this allows the user to put null terminators in the middle of the string
                // if they wanted to do that for some reason
                if (CURRENT_DIRECTIVE == STRING) {
                    data.size = string_length;
                }
                else if (CURRENT_DIRECTIVE == STRING_NT) {
                    data.size = string_length+1;
                }

                if (process_data(&data, CURRENT_DIRECTIVE, argument, assembler->symbol_table) == 0) {
                    free(argument);
                    return 0;
                }

                // Add any necessary padding
                if (data_pad(data, list) == 0) {
                    free(argument);
                    return 0;
                }

                // Write the label(s)
                if (label_count != 0) {
                    for (size_t i = 0; i < label_count; i++) {
                        if (st_add_symbol(assembler->symbol_table, labels[i].str, list->data_offset, CURRENT_SEGMENT, LOCAL) == 0) {
                            free(argument);
                            return 0;
                        }
                    }
                }

                // Add to data list and increment data_addr
                if (add_data(list, data) == 0) {
                    free(argument);
                    return 0;
                }

            }
            argc++;
            memset(labels, '\0', sizeof(labels));
            label_count = 0;
        }

        token = tokenize(NULL, ' ');
    }

    if (CURRENT_DIRECTIVE == ALIGN || CURRENT_DIRECTIVE == SPACE) CURRENT_DIRECTIVE = WORD; // .align and .space directives don't survive next line

    for (size_t i = 0; i < label_count; i++) {
        string_destroy(&labels[i]);
    }

    free(argument);

    return 1;
}

/* === SECOND PASS TEXT SEGMENT === */

// Returns the 32-bit machine code representation of the Instruction, or -1 on failure.
uint32_t convert_instruction(const Instruction instruction, const Assembler* assembler, const uint32_t current_addr) {
    // Get function description
    const InstrDesc *instruction_desc = it_lookup(assembler->instruction_table, instruction.mnemonic);
    if (instruction_desc == NULL) return -1;

    switch (instruction_desc->format) {
        case R:
            return convert_rtype(instruction, instruction_desc);
        case I:
            return convert_itype(instruction, assembler->relocation_table, instruction_desc, current_addr, CURRENT_SEGMENT);
        case J:
            return convert_jtype(instruction, assembler->relocation_table, instruction_desc, current_addr, CURRENT_SEGMENT);
        default:
            raise_error(NOERR, NULL, __FILE__);
            return -1;
    }
}

// Goes through every instruction and writes its 32-bit machine code to the file. Returns 0 on failure
int write_instruction_list(FILE *file, const Assembler *assembler) {
    uint32_t current_addr = 0;
    const InstructionList *list;
    if (CURRENT_SEGMENT == TEXT) {
        list = assembler->instruction_list;
    }
    else if (CURRENT_SEGMENT == KTEXT) {
        list = assembler->kernel_text;
    }
    else return 0;

    for (size_t i = 0; i < list->len; i++) {
        const Instruction instruction = list->list[i];
        ERROR_HANDLER.line = instruction.line;

        // Convert to machine code
        const uint32_t machine_code = convert_instruction(instruction, assembler, current_addr);
        if (machine_code == (uint32_t) -1) {
            return 0;
        }

        // Write 32-bit instruction to file
        if (write_word(file, machine_code) == 0) {
            ERROR_HANDLER.err_code = FILE_IO;
            return 0;
        }

        current_addr += 4;
    }
    return 1;
}

/* === SECOND PASS DATA SEGMENT === */

// Writes a Data structure to the file
int write_data(FILE *file, Data data, RelocationTable *relocation_table, const uint32_t current_offset) {
    if (data.isSymbol) {

        // Requires R_32 relocation
        Symbol *s = data.value.symbol;
        RelocationEntry reloc;

        switch (data.type) {
            // TODO: byte and half
            case WORD:
                data.value.word = 0;
                re_init(&reloc, s->index, current_offset, CURRENT_SEGMENT, R_32);
                break;
            default:
                raise_error(ARGS_INV, NULL, __FILE__);
                return 0;
        }
        rt_add(relocation_table, reloc);
    }

    unsigned long success;
    if (data.type == STRING || data.type == STRING_NT) {
        success = write_string(file, data.value.string, data.size);
        if (success == 0) {
            ERROR_HANDLER.err_code = FILE_IO;
            return 0;
        }
        return 1;
    }

    if (data.type == SPACE) {
        for (size_t i = 0; i < data.size; i++) {
            success = write_byte(file, 0);
            if (success == 0) {
                ERROR_HANDLER.err_code = FILE_IO;
                return 0;
            }
        }
        return 1;
    }

    success = fwrite(&data.value, data.size, 1, file);
    if (success == 0) {
        ERROR_HANDLER.err_code = FILE_IO;
        return 0;
    }
    return 1;

}

// Goes through every Data structure in the list and writes it to file. Returns 0 on failure or -1 on file IO failure.
int write_data_list(FILE *file, Assembler *assembler) {
    uint32_t current_offset = 0;
    DataList *list;
    if (CURRENT_SEGMENT == DATA) {
        list = assembler->data_list;
    }
    else if (CURRENT_SEGMENT == KDATA) {
        list = assembler->kernel_data;
    } else return 0;
    for (size_t i = 0; i < list->len; i++) {
        const Data data = list->list[i];
        ERROR_HANDLER.line = data.line;

        const int success = write_data(file, data, assembler->relocation_table, current_offset);
        if (success <= 0) return success;
        current_offset += data.size;
    }
    // Add padding bytes until word-aligned
    while (current_offset % 4 != 0) {
        uint8_t x = 0;
        fwrite(&x, sizeof(x), 1, file);
        current_offset++;
    }
    list->data_offset = current_offset;
    return 1;
}

/* === MAIN === */

// Parses the output of the preprocessor into the symbol table, instruction list, and data list.
int assembler_first_pass(Assembler *assembler) {

    // Loop through each individual line in the file
    Line *line = assembler->preprocessed->head;
    while (line != NULL) {
        ERROR_HANDLER.line = line;

        // preprocessor sometimes leaves trailing spaces; i should fix this there
        char *text = line_get_str(line);
        if (text == NULL) return 0;
        if (text[strlen(text)-1] == ' ') text[strlen(text)-1] = '\0';

        // Read directive
        if (text[0] == '.') {
            char directive[16];
            char c = text[1];
            int j = 0;
            while (!isspace(c) && c != '\0') {
                directive[j] = c;
                j++;
                c = text[j+1];
            }
            directive[j] = '\0';

            if (strcmp(directive, "text") == 0) {
                CURRENT_SEGMENT = TEXT;
                goto continue_line;
            }
            if (strcmp(directive, "data") == 0) {
                CURRENT_SEGMENT = DATA;
                goto continue_line;
            }
            if (strcmp(directive, "ktext") == 0) {
                CURRENT_SEGMENT = KTEXT;
                goto continue_line;
            }
            if (strcmp(directive, "kdata") == 0) {
                CURRENT_SEGMENT = KDATA;
                goto continue_line;
            }
            if (strcmp(directive, "globl") == 0) {
                // Add all arguments to symbol table as global undefined symbols
                char line_cpy[strlen(text)+1];
                strcpy(line_cpy,text);
                const char *token = tokenize(line_cpy, ' ');
                token = tokenize(NULL, ' '); // tokenize again to skip the directive
                if (token == NULL) {
                    raise_error(ARGS_INV, NULL, __FILE__);
                    return 0;
                }
                while (token != NULL) {
                    Symbol *psym = st_get_symbol(assembler->symbol_table, token);
                    if (psym == NULL) {
                        st_add_symbol(assembler->symbol_table, token, 0, UNDEF, GLOBAL);
                    } else {
                        psym->binding = GLOBAL;
                    }

                    token = tokenize(NULL, ' ');
                }
                goto continue_line;
            }
            if (CURRENT_SEGMENT != DATA && CURRENT_SEGMENT != KDATA) { // Any other directive must be in the data segment
                raise_error(TOKEN_ERR, directive, __FILE__);
                return 0;
            }
        }

        // TEXT
        if (CURRENT_SEGMENT == TEXT || CURRENT_SEGMENT == KTEXT) {
            try(read_text(assembler, line), 0);
        }

        // DATA
        else if (CURRENT_SEGMENT == DATA || CURRENT_SEGMENT == KDATA) {
            try(read_data(assembler, line), 0);
        }

        continue_line:
        line = line->next;
    }

    return 1;
}

// Processes the output of the first pass and writes the result to file
int assembler_second_pass(Assembler *assembler, const char *output) {

    ERROR_HANDLER.line = NULL;

    // === Open output file ===
    FILE *file = fopen(output, "wb");
    if (file == NULL) {
        raise_error(FILE_IO, output, __FILE__);
        return 0;
    }

    // Move to end of header (written last)
    fseek(file, sizeof(struct mof_header), SEEK_SET);

    // === Write Instructions ===
    CURRENT_SEGMENT = TEXT;
    int success = write_instruction_list(file, assembler);
    if (success == 0) {
        if (ERROR_HANDLER.err_code == FILE_IO) {
            raise_error(FILE_IO, output, __FILE__);
        }
        fclose(file);
        return 0;
    }

    // == Write Data ===
    CURRENT_SEGMENT = DATA;
    success = write_data_list(file, assembler);
    if (success == 0) {
        if (ERROR_HANDLER.err_code == FILE_IO) {
            raise_error(FILE_IO, output, __FILE__);
        }
        fclose(file);
        return 0;
    }

    // === Write Kernel Text ===
    CURRENT_SEGMENT = KTEXT;
    success = write_instruction_list(file, assembler);
    if (success == 0) {
        if (ERROR_HANDLER.err_code == FILE_IO) {
            raise_error(FILE_IO, output, __FILE__);
        }
        fclose(file);
        return 0;
    }

    // === Write Kernel Data ===
    CURRENT_SEGMENT = KDATA;
    success = write_data_list(file, assembler);
    if (success == 0) {
        if (ERROR_HANDLER.err_code == FILE_IO) {
            raise_error(FILE_IO, output, __FILE__);
        }
        fclose(file);
        return 0;
    }

    // === Write Relocation Table ===
    success = write_reloc_table(file, assembler->relocation_table);
    if (success == 0) {
        if (ERROR_HANDLER.err_code == FILE_IO) {
            raise_error(FILE_IO, output, __FILE__);
        }
        fclose(file);
        return 0;
    }

    // === Write Symbol Table ===
    success = write_symbol_table(file, assembler->symbol_table);
    if (success == 0) {
        if (ERROR_HANDLER.err_code == FILE_IO) {
            raise_error(FILE_IO, output, __FILE__);
        }
        fclose(file);
        return 0;
    }

    // strtab_debug(assembler->symbol_table->string_table);

    // === Write Header ===
    rewind(file);
    struct mof_header header;
    header.magic = MOF_MAGIC;
    header.text = assembler->instruction_list->text_offset;
    header.data = assembler->data_list->data_offset;
    header.ktext = assembler->kernel_text->text_offset;
    header.kdata = assembler->kernel_data->data_offset;
    header.rels = assembler->relocation_table->len * MOF_RELOCSIZE;
    header.syms = assembler->symbol_table->size * MOF_SYMSIZE;
    header.entry = TEXT_START;
    fwrite(&header, sizeof(header), 1, file);

    fclose(file);
    return 1;
}

// Converts the output of the preprocessor into machine code and writes it to file
int assemble(Text *preprocessed, const char *output) {
    Assembler assembler;
    if (assembler_init(&assembler, preprocessed) == 0) {
        assembler_destroy(&assembler);
        return 0;
    }

    if (assembler_first_pass(&assembler) == 0) {
        assembler_destroy(&assembler);
        return 0;
    }

    // Check for undefined local symbols and make global
    // This behavior essentially automatically imports any undefined symbol
    // in the hopes that the linker will find them
    for (int i = 0; i < SYMBOL_TABLE_SIZE; i++) {
        SymbolBucket *cur = assembler.symbol_table->buckets[i];
        while (cur != NULL) {
            if (cur->item.segment == UNDEF) {
                cur->item.binding = GLOBAL;
            }
            cur = cur->next;
        }
    }

    // dl_debug(assembler.data_list);
    // dl_debug(assembler.kernel_data);
    // st_debug(assembler.symbol_table);
    // il_debug(assembler.instruction_list);

    if (assembler_second_pass(&assembler, output) == 0) {
        assembler_destroy(&assembler);
        return 0;
    }

    // st_debug(assembler.symbol_table);
    // rt_debug(assembler.relocation_table, assembler.symbol_table);

    assembler_destroy(&assembler);
    return 1;
}

// Allocates memory for and initializes the components of the assembler given the output of the preprocessor
int assembler_init(Assembler *assembler, Text *preprocessed) {
    CURRENT_SEGMENT = TEXT;
    CURRENT_DIRECTIVE = WORD;

    assembler->preprocessed = preprocessed;
    assembler->symbol_table = NULL;
    assembler->data_list = NULL;
    assembler->instruction_list = NULL;
    assembler->instruction_table = NULL;
    assembler->relocation_table = NULL;

    // Initialize symbol table
    SymbolTable *symbol_table = malloc(sizeof(SymbolTable));
    if (symbol_table == NULL) {
        raise_error(MEM, NULL, __FILE__);
        return 0;
    }
    try(st_init(symbol_table), 0);
    assembler->symbol_table = symbol_table;

    // Initialize instruction list
    InstructionList *instruction_list = malloc(sizeof(InstructionList));
    if (instruction_list == NULL) {
        raise_error(MEM, NULL, __FILE__);
        return 0;
    }
    try(il_init(instruction_list, 0), 0);
    assembler->instruction_list = instruction_list;

    // Initialize data list
    DataList *data_list = malloc(sizeof(DataList));
    if (data_list == NULL) {
        raise_error(MEM, NULL, __FILE__);
        return 0;
    }
    try(dl_init(data_list, 0), 0);
    assembler->data_list = data_list;

    // Initialize kernel text
    InstructionList *kernel_text = malloc(sizeof(InstructionList));
    if (kernel_text == NULL) {
        raise_error(MEM, NULL, __FILE__);
        return 0;
    }
    try(il_init(kernel_text, 0), 0);
    assembler->kernel_text = kernel_text;

    // Initialize kernel data
    DataList *kernel_data = malloc(sizeof(DataList));
    if (kernel_data == NULL) {
        raise_error(MEM, NULL, __FILE__);
        return 0;
    }
    try(dl_init(kernel_data, 0), 0);
    assembler->kernel_data = kernel_data;

    // Initialize instruction table
    InstructionTable *instruction_table = malloc(sizeof(InstructionTable));
    if (instruction_table == NULL) {
        raise_error(MEM, NULL, __FILE__);
        return 0;
    }
    try(it_create(instruction_table), 0);
    assembler->instruction_table = instruction_table;

    // Initialize relocation table
    RelocationTable *relocation_table = malloc(sizeof(RelocationTable));
    if (relocation_table == NULL) {
        raise_error(MEM, NULL, __FILE__);
        return 0;
    }
    try(rt_init(relocation_table), 0);
    assembler->relocation_table = relocation_table;

    return 1;
}

// Frees the resources of the assembler and its components
void assembler_destroy(Assembler *assembler) {
    if (assembler->data_list != NULL) {
        dl_destroy(assembler->data_list);
        free(assembler->data_list);
    }
    if (assembler->kernel_data != NULL) {
        dl_destroy(assembler->kernel_data);
        free(assembler->kernel_data);
    }
    if (assembler->instruction_list != NULL) {
        il_destroy(assembler->instruction_list);
        free(assembler->instruction_list);
    }
    if (assembler->kernel_text != NULL) {
        il_destroy(assembler->kernel_text);
        free(assembler->kernel_text);
    }
    if (assembler->symbol_table != NULL) {
        st_destroy(assembler->symbol_table);
        free(assembler->symbol_table);
    }
    if (assembler->instruction_table != NULL) {
        it_destroy(assembler->instruction_table);
        free(assembler->instruction_table);
    }
    if (assembler->relocation_table != NULL) {
        rt_destroy(assembler->relocation_table);
        free(assembler->relocation_table);
    }
}

void assembler_debug(const Assembler *assembler) {

    if (assembler->symbol_table != NULL) {
        st_debug(assembler->symbol_table);
    } else {
        printf("No symbol table found\n");
    }

    if (assembler->data_list != NULL) {
        printf("User data:\n");
        dl_debug(assembler->data_list);
    } else {
        printf("No data list found\n");
    }

    if (assembler->kernel_data != NULL) {
        printf("Kernel data:\n");
        dl_debug(assembler->kernel_data);
    } else {
        printf("No kernel data found\n");
    }

    if (assembler->instruction_list != NULL) {
        printf("User text:\n");
        il_debug(assembler->instruction_list);
    } else {
        printf("No instruction list found\n");
    }

    if (assembler->kernel_text != NULL) {
        printf("Kernel text:\n");
        il_debug(assembler->kernel_text);
    } else {
        printf("No kernel text found\n");
    }

    if (assembler->relocation_table != NULL) {
        rt_debug(assembler->relocation_table, assembler->symbol_table);
    } else {
        printf("No relocation table found\n");
    }
}
